### ISSUE TITLE
Menysystem 

### ISSUE THREAD

**Issue by pmleinan** [sjoholt/Assignment5#1]
Halvferdig

**Comment by sjoholt** [comment]
Etter funksjoner er ferdig, skal main menu dukke opp. Eller lignende. 
Main menu skrives også ut når du går INN i en funksjon. Isje bra.

**Comment by sjoholt** [comment]
Vi må prøve å rydde opp i hvordan menyen blir printet her og der. Det er litt tilfeldig når noe dukker opp nå. Om du kjører en funksjon, bør en av og til (eller alltid) få listet opp menyevalgene på rette nivået når funksjonen er ferdigkjørt.

**Comment by pmleinan** [comment]
Fikset
